Monthly services
hadiaHani/myBuildingApp pull request #15
Opened 2023-06-26 14:35 UTC by hadiaHani

2023-06-26 14:47 UTC, Muhanned-Anwar approved these changes

2023-06-29 20:38 UTC, DevHeyamAwad approved these changes

2023-07-05 14:18 UTC, Muhanned-Anwar approved these changes

2023-07-05 18:08 UTC, DevHeyamAwad approved these changes

2023-07-07 18:18 UTC, DevHeyamAwad approved these changes

2023-07-07 19:48 UTC, Muhanned-Anwar approved these changes

2023-07-09 11:07 UTC, Muhanned-Anwar requested changes

2023-07-09 11:07 UTC, Muhanned-Anwar commented on lib/features/monthly_services/presentation/view/services_view.dart
> +                            "${ManagerStrings.type}${monthlyServicesDetailesList[index].type.toString() == "services" ? ManagerStrings.monthleyServicesType : " "}",
create function in controller for this logic

2023-07-09 11:07 UTC, Muhanned-Anwar commented on lib/features/monthly_services/presentation/view/services_view.dart
> +                            "${ManagerStrings.required} ${(double.parse(monthlyServicesDetailesList[index].remain!) + double.parse(monthlyServicesDetailesList[index].paid!)).toStringAsFixed(1)}",
move logic to controller in function then import function here

2023-07-09 11:07 UTC, Muhanned-Anwar commented on lib/features/monthly_services/presentation/view/services_view.dart
> +                            "${ManagerStrings.collector} ${(double.parse(monthlyServicesDetailesList[index].paid!))}",
move to controller as before

2023-07-09 11:07 UTC, Muhanned-Anwar commented on lib/features/monthly_services/presentation/view/services_view.dart
> +                            "${ManagerStrings.residual} ${(double.parse(monthlyServicesDetailesList[index].remain!))}",
move to controller

2023-07-09 11:07 UTC, Muhanned-Anwar commented on lib/main.dart
> +          Locale('ar', 'SA'),
move locale as constants

2023-07-09 13:08 UTC, Muhanned-Anwar approved these changes
Good Job 👍

2023-07-10 10:55 UTC, Muhanned-Anwar approved these changes

2023-07-10 11:57 UTC, merged